**Домашнее задание «Библиотека numpy. Вычислительные задачи»**

Преподаватель: Константин Башевой

**Задание 1**

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

In [9]:
n = 10
a = np.arange (n-1, -1, -1)
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
b = np.arange (0,n)
reversed_b = b[::-1]
reversed_b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [24]:
matrix = np.diag (np.arange(n,0,-1), k = 0)
matrix

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1]])

In [26]:
trace = np.trace(matrix)
trace

55

In [30]:
i = 0
sum_diag = 0

for el in matrix:
        sum_diag += el[i]
        i += 1

sum_diag

55

**Задание 3**

Решите систему уравнений: \
4x + 2y + z = 4 \
x + 3y = 12 \
5y + 4z = -3

In [31]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
x = np.linalg.inv(a).dot(b)

print(x)


[ 0.46666667  3.84444444 -5.55555556]


**Задание 4**

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем. \
Матрица в виде numpy array:

In [32]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [33]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [46]:
from numpy.linalg import norm

In [72]:
cosine_list = []

for el in users_stats:
        cosine = np.dot(next_user_stats, el)/(norm(next_user_stats)*norm(el))
        print("Cosine Similarity:", cosine)
        cosine_list.append (cosine)

max_cosine = max(cosine_list)
res = [i+1 for i, j in enumerate(cosine_list) if j == max_cosine] # user_id начинается с 1, поэтому прибавляю 1 к индексу

print(f'ID пользователя со схожими покупками:{res[0]}')

Cosine Similarity: 0.19999999999999996
Cosine Similarity: 0.8451542547285165
Cosine Similarity: 0.3999999999999999
Cosine Similarity: 0.7905694150420948
Cosine Similarity: 0.3999999999999999
Cosine Similarity: 0.0
Cosine Similarity: 0.0
Cosine Similarity: 0.9486832980505138
Cosine Similarity: 0.0
Cosine Similarity: 0.0
ID пользователя со схожими покупками:8


**Вариант решения 2 (с расстоянием Левенштейна)**

In [ ]:
pip install python-levenshtein

In [62]:
import Levenshtein

In [71]:
distance_list = []

for el in users_stats:
        print(Levenshtein.distance (next_user_stats, el))
        distance_list.append(Levenshtein.distance (next_user_stats, el))

min_distance = min(distance_list)
res = [i+1 for i, j in enumerate(distance_list) if j == min_distance] # user_id начинается с 1, поэтому прибавляю 1 к индексу

print(f'ID пользователя со схожими покупками:{res[0]}')

2
2
2
3
2
3
3
1
5
5
ID пользователя со схожими покупками:8
