**Домашнее задание "Линейная алгебра. Матрицы".**

Уровень 0:

**Задание 1**\
- Создайте матрицу 3 на 3, заполненную числами от 1 до 9
- Прибавьте к ней матрицу с единицами на диагонале
- Умножьте полученную матрицу на вектор (1, 2, 3)
- Вычислить транспонированную матрицу от полученной в результате прибавления матрицы
- Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [1]:
import numpy as np
import sympy as sym

In [5]:
A = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
B = np.eye(3)
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
C = A + B
C

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [40]:
C @ [1,2,3]

array([15., 34., 53.])

In [10]:
C.T

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [12]:
D = np.linalg.inv(C)
D

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

Проверим:

In [13]:
C @ D

array([[ 1.00000000e+00, -3.33066907e-16,  6.66133815e-16],
       [-5.32907052e-15,  1.00000000e+00,  1.33226763e-15],
       [-1.77635684e-15, -1.11022302e-15,  1.00000000e+00]])

Уровень 1:

**Задание 2**\
Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2],
              [1, 3]])\
print(m)

In [14]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [15]:
np.linalg.eig(m)

(array([1., 4.]), array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

**Задание 3**\
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

m = np.array([[a,b], [c,d]])\
det = a * d - c * b

В нашем случае определитель = 1, тогда

a * d = 1 + c * b

Можем взять два любых числа для координат векторов и на основе их вычислить остальные.
Предположим, что a = 2, d = 3, тогда

2 * 3 = 1 + c * b\
1 + c * b = 6\
c * b = 5

Тогда, например, подходит матрица:
m = np.array([[2,1],[5,3]])

Проверим

In [32]:
m = np.array([[2,5],
              [1,3]])
m

array([[2, 5],
       [1, 3]])

In [33]:
np.linalg.det(m)

1.0

In [34]:
np.linalg.det(m.T)

1.0000000000000009

Можно придумать еще варианты, если подобрать значение b для с в диапазоне от (1 до n)

In [39]:
c = int
b = float

for c in range (1,11):
    b = 5/c
    print(f'c = {c}')
    print(f'b = {b}')


c = 1
b = 5.0
c = 2
b = 2.5
c = 3
b = 1.6666666666666667
c = 4
b = 1.25
c = 5
b = 1.0
c = 6
b = 0.8333333333333334
c = 7
b = 0.7142857142857143
c = 8
b = 0.625
c = 9
b = 0.5555555555555556
c = 10
b = 0.5
